/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add` | `/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BuyNBorrow/borrow` | `/BuyNBorrow/borrow`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BuyNBorrow/buy` | `/BuyNBorrow/buy`; params?: Router.UnknownInputParams; } | { pathname: `/signIn/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signUp/signup`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/products/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/products/chat/[chat]`, params: Router.UnknownInputParams & { chat: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add` | `/add`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/BuyNBorrow/borrow` | `/BuyNBorrow/borrow`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/BuyNBorrow/buy` | `/BuyNBorrow/buy`; params?: Router.UnknownOutputParams; } | { pathname: `/signIn/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/signUp/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/products/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/products/chat/[chat]`, params: Router.UnknownOutputParams & { chat: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add${`?${string}` | `#${string}` | ''}` | `/add${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chats${`?${string}` | `#${string}` | ''}` | `/chats${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/BuyNBorrow/borrow${`?${string}` | `#${string}` | ''}` | `/BuyNBorrow/borrow${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/BuyNBorrow/buy${`?${string}` | `#${string}` | ''}` | `/BuyNBorrow/buy${`?${string}` | `#${string}` | ''}` | `/signIn/signin${`?${string}` | `#${string}` | ''}` | `/signUp/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add` | `/add`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BuyNBorrow/borrow` | `/BuyNBorrow/borrow`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BuyNBorrow/buy` | `/BuyNBorrow/buy`; params?: Router.UnknownInputParams; } | { pathname: `/signIn/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signUp/signup`; params?: Router.UnknownInputParams; } | `/+not-found` | `/products/${Router.SingleRoutePart<T>}` | `/products/chat/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/products/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/products/chat/[chat]`, params: Router.UnknownInputParams & { chat: string | number; } };
    }
  }
}
